### ISSUE TITLE
Remove push extension method 

### ISSUE THREAD

**Issue by carmas123** [iampawan/VelocityX#177]
After you bad decision to remove vxNav extension to migrate all to `go_router` now we are forced to change all our app that use this extension with many days of work!!!

After removed this functionality you could remove also all navigator extensions from the source code otherwise we can't use the go_router extension method like "push".

Regards

**Comment by iampawan** [comment]
Hi @carmas123, we really apologies for all the inconvenience it caused you after the removal of VxNav but we care about each all of you. You let me know how I can help you to not redo everything from the start. I can also publish a separate version or branch with the removed vxnav. The decision we took because there were some issues specifically on web and we found that go_router is a better alternative for all navigation use cases. Having said that, you can still suggest us what works for you and we would be happy to do the needful.

**Comment by carmas123** [comment]
Hi @iampawan and thank you for fast reply.
The best thing to do now would be to proceed with "go_router" and not go back.
I just posted a pull request to remove some orphaned navigator-related extensions that conflict with the "go_router" extensions, so maybe the thing to do soon would be to remove any references to navigation from VelocityX

**Comment by iampawan** [comment]
Yes makes sense. I will do it and thanks for understanding, it's all for a better future
