### ISSUE TITLE
Can't set begin and end properties for linear gradient with VxBox

### ISSUE THREAD

**Issue by jitendrapurohit12** [iampawan/VelocityX#46]
Like normal BoxDecoration, we can't set the start and end of the linear gradient. It's always set from left-center to right-center.

**To Reproduce**
VxBox().linearGradient(
                    [
                      Colors.black.withOpacity(0.8),
                      Colors.black.withOpacity(0)
                    ],
                  ).make(),

 - OS: Android, iOS

**Comment by jitendrapurohit12** [comment]
Though I used .withGradient which works perfectly but having all Linear Gradient properties will help imo.

**Comment by iampawan** [comment]
Hey @jitendrapurohit12 thanks for your first issue. VelocityX was made with general usecases first in mind like .linearGradient with the most used way rather than exposing everything which makes it a tough job. Rather I decided to give full control using something like .withGradient or .withDecoration so that if those general use cases don't match they you can customize it. But I'll look for more such feedbacks and would love to add these in future. Closing for now.
